### ISSUE TITLE
Provide new props to declare time of animation

### ISSUE THREAD

**Issue by romadryud** [czystyl/react-native-reanimated-flip#37]
Hi, thank you for your package. I have an idea to add a time prop in ms which allows controlling the speed/duration of the animation. Please let me know what you think about that.

**Comment by romadryud** [comment]
So I will close the issue because I don't receive an answer for 15 days.

**Comment by czystyl** [comment]
Hey! Sorry, @romadryud, for the late response - I was off during the holiday! 

I think it's a great idea! We used it without adjusting the time, but that might be the case for some projects!
